package go_pgdump

import (
	"database/sql"
	"fmt"
	"sort"
	"strings"
)

// queryer is satisfied by both *sql.DB and *sql.Tx, letting catalog helpers
// run either against a live connection or an in-flight read-only transaction.
type queryer interface {
	Query(query string, args ...interface{}) (*sql.Rows, error)
	QueryRow(query string, args ...interface{}) *sql.Row
}

const getTablesQuery = `
SELECT c.relname
FROM pg_catalog.pg_class c
JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'public'
  AND c.relkind = 'r'
  AND NOT c.relispartition
ORDER BY c.relname;
`

// getTables lists ordinary (base) tables in the public schema, excluding
// views, materialized views, partitioned parents, foreign tables and
// partition children.
func getTables(q queryer) ([]string, error) {
	rows, err := q.Query(getTablesQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var tables []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		tables = append(tables, name)
	}
	return tables, rows.Err()
}

const getColumnsQuery = `
SELECT a.attname, a.attnum,
    pg_catalog.format_type(a.atttypid, a.atttypmod) AS data_type,
    a.attnotnull,
    pg_catalog.pg_get_expr(ad.adbin, ad.adrelid) AS default_expr,
    a.attidentity, a.attgenerated
FROM pg_catalog.pg_attribute a
LEFT JOIN pg_catalog.pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
WHERE a.attrelid = $1::regclass AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum;
`

type column struct {
	name         string
	dataType     string
	notNull      bool
	defaultExpr  sql.NullString
	identityKind string // "" | "a" | "d"
	generated    string // "" | "s"
}

// columnDef renders this column's fragment of a CREATE TABLE statement
// (everything after the column name that isn't a table-level constraint).
func (c column) def() string {
	part := quoteIdent(c.name) + " " + c.dataType

	switch {
	case c.identityKind == "a":
		part += " GENERATED ALWAYS AS IDENTITY"
	case c.identityKind == "d":
		part += " GENERATED BY DEFAULT AS IDENTITY"
	case c.generated == "s":
		part += fmt.Sprintf(" GENERATED ALWAYS AS (%s) STORED", c.defaultExpr.String)
	case c.defaultExpr.Valid:
		part += " DEFAULT " + c.defaultExpr.String
	}

	if c.notNull {
		part += " NOT NULL"
	}
	return part
}

// isStoredGenerated reports whether this column is a `GENERATED ALWAYS AS
// (...) STORED` column, which Postgres computes itself and which therefore
// must be excluded from COPY's column list and data SELECT.
func (c column) isStoredGenerated() bool {
	return c.generated == "s"
}

func getColumns(q queryer, qualifiedTable string) ([]column, error) {
	rows, err := q.Query(getColumnsQuery, qualifiedTable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var columns []column
	for rows.Next() {
		var c column
		var attnum int
		if err := rows.Scan(&c.name, &attnum, &c.dataType, &c.notNull, &c.defaultExpr, &c.identityKind, &c.generated); err != nil {
			return nil, err
		}
		columns = append(columns, c)
	}
	return columns, rows.Err()
}

// createTableDDL builds a `CREATE TABLE` statement for the given table
// (schema-qualified as "public"."<table>") and returns the ordered list of
// column names that should be included in COPY data (excluding any stored
// generated columns, which Postgres computes itself).
func createTableDDL(q queryer, table string) (ddl string, copyColumns []string, err error) {
	qualifiedTable := `"public".` + quoteIdent(table)

	columns, err := getColumns(q, qualifiedTable)
	if err != nil {
		return "", nil, err
	}

	defs := make([]string, 0, len(columns))
	for _, c := range columns {
		defs = append(defs, "    "+c.def())
		if !c.isStoredGenerated() {
			copyColumns = append(copyColumns, c.name)
		}
	}

	ddl = fmt.Sprintf("CREATE TABLE %s (\n%s\n);\n", qualifiedTable, strings.Join(defs, ",\n"))
	return ddl, copyColumns, nil
}

const getConstraintsQuery = `
SELECT con.conname, con.contype, pg_catalog.pg_get_constraintdef(con.oid, true)
FROM pg_catalog.pg_constraint con
WHERE con.conrelid = $1::regclass AND con.contype IN ('p','u','c','f')
ORDER BY con.contype, con.conname;
`

// constraintTypeRank orders constraint emission as PK -> UNIQUE -> CHECK ->
// FK. FKs must come last so all referenced tables/rows already exist by the
// time the constraint is added; PK/UNIQUE come first since they back the
// indexes FKs need.
var constraintTypeRank = map[string]int{"p": 0, "u": 1, "c": 2, "f": 3}

type constraint struct {
	name       string
	conType    string // "p" | "u" | "c" | "f"
	definition string
}

func (c constraint) alterStatement(qualifiedTable string) string {
	return fmt.Sprintf("ALTER TABLE %s ADD CONSTRAINT %s %s;", qualifiedTable, quoteIdent(c.name), c.definition)
}

func getConstraints(q queryer, qualifiedTable string) ([]constraint, error) {
	rows, err := q.Query(getConstraintsQuery, qualifiedTable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var constraints []constraint
	for rows.Next() {
		var c constraint
		if err := rows.Scan(&c.name, &c.conType, &c.definition); err != nil {
			return nil, err
		}
		constraints = append(constraints, c)
	}
	return constraints, rows.Err()
}

// orderConstraints returns constraints sorted into PK -> UNIQUE -> CHECK ->
// FK phase order (stable within each type), regardless of the order they
// were retrieved in.
func orderConstraints(constraints []constraint) []constraint {
	ordered := make([]constraint, len(constraints))
	copy(ordered, constraints)
	sort.SliceStable(ordered, func(i, j int) bool {
		return constraintTypeRank[ordered[i].conType] < constraintTypeRank[ordered[j].conType]
	})
	return ordered
}

const getIndexesQuery = `
SELECT pg_catalog.pg_get_indexdef(i.indexrelid)
FROM pg_catalog.pg_index i
WHERE i.indrelid = $1::regclass AND NOT i.indisprimary
  AND NOT EXISTS (SELECT 1 FROM pg_catalog.pg_constraint c WHERE c.conindid = i.indexrelid)
ORDER BY i.indexrelid::regclass::text;
`

const getOwnedSequencesQuery = `
SELECT s.relname AS seq_name, a.attname AS col_name
FROM pg_catalog.pg_depend d
JOIN pg_catalog.pg_class s      ON s.oid = d.objid       AND s.relkind = 'S'
JOIN pg_catalog.pg_class t      ON t.oid = d.refobjid
JOIN pg_catalog.pg_attribute a  ON a.attrelid = t.oid    AND a.attnum = d.refobjsubid
WHERE d.classid    = 'pg_class'::regclass
  AND d.refclassid = 'pg_class'::regclass
  AND d.deptype IN ('a','i')
  AND t.oid = $1::regclass
ORDER BY s.relname;
`

type ownedSequence struct {
	seqName string
	colName string
}

func getOwnedSequences(q queryer, qualifiedTable string) ([]ownedSequence, error) {
	rows, err := q.Query(getOwnedSequencesQuery, qualifiedTable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var seqs []ownedSequence
	for rows.Next() {
		var s ownedSequence
		if err := rows.Scan(&s.seqName, &s.colName); err != nil {
			return nil, err
		}
		seqs = append(seqs, s)
	}
	return seqs, rows.Err()
}

// readSequenceState reads a sequence's own last_value/is_called, mirroring
// what pg_dump does - this restores the exact source cursor position, which
// matters when whereClauseForTables filtered out the highest-id rows (a
// MAX(col) recomputation from dumped data would under-restore in that case).
func readSequenceState(q queryer, qualifiedSeqName string) (lastValue int64, isCalled bool, err error) {
	row := q.QueryRow(fmt.Sprintf("SELECT last_value, is_called FROM %s", qualifiedSeqName))
	err = row.Scan(&lastValue, &isCalled)
	return lastValue, isCalled, err
}

// quoteLiteral escapes a value for use inside a single-quoted SQL string
// literal (as opposed to quoteIdent, which escapes identifiers).
func quoteLiteral(s string) string {
	return strings.ReplaceAll(s, "'", "''")
}

func setvalStatement(qualifiedSeqName string, lastValue int64, isCalled bool) string {
	return fmt.Sprintf("SELECT pg_catalog.setval('%s', %d, %t);", quoteLiteral(qualifiedSeqName), lastValue, isCalled)
}

// sequenceRestoreStatements finds every sequence owned by a column of the
// given table (covering both classic SERIAL and GENERATED ... AS IDENTITY)
// and returns the `setval` statements needed to restore their exact live
// state after data load.
func sequenceRestoreStatements(q queryer, qualifiedTable string) ([]string, error) {
	seqs, err := getOwnedSequences(q, qualifiedTable)
	if err != nil {
		return nil, err
	}

	statements := make([]string, 0, len(seqs))
	for _, s := range seqs {
		qualifiedSeqName := `"public".` + quoteIdent(s.seqName)
		lastValue, isCalled, err := readSequenceState(q, qualifiedSeqName)
		if err != nil {
			return nil, err
		}
		statements = append(statements, setvalStatement(qualifiedSeqName, lastValue, isCalled))
	}
	return statements, nil
}

// getIndexes lists secondary (non-PK, non-constraint-backed) indexes on the
// given table as complete `CREATE INDEX ...;` statements.
func getIndexes(q queryer, qualifiedTable string) ([]string, error) {
	rows, err := q.Query(getIndexesQuery, qualifiedTable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var defs []string
	for rows.Next() {
		var def string
		if err := rows.Scan(&def); err != nil {
			return nil, err
		}
		defs = append(defs, def+";")
	}
	return defs, rows.Err()
}
