name: "Release Tag"
on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: pterm/release-tag-action@main
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
