on:
  push:
    branches:
      - main
      - master

name: Create Git Tag
jobs:
  versioner:
    runs-on: ubuntu-latest
    steps:
      - name: Update Version
        uses: pterm/tag-action@main
        env:
          ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
